<div id="contentLogin">
    <p>
        Bonjour, pour acceder à l'application, veuillez vous identifier.
        <span>
            Mot de passe oublié ? Nouveau membre ? Pour toute question, veuillez contacter le service informatique.
        </span>
    </p>
    <?php if ($this->error_auth): ?>
    <div id="auth_form_error">
        <?php echo $this->message; ?>
    </div>
    <?php endif; ?>
<?php 
    //$this->formLogin->setAction('login/loginuser');
    echo $this->formLogin;
?>
</div>