<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <?php echo $this->doctype(); ?>
<head>
    <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/reset.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/style_client.css'); ?>    
    <?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/style_help.css"); ?>
    <?php echo $this->headLink(); ?>  
    <?php echo $this->headScript(); ?>
    <?php echo $this->headTitle() ?>
</head>
<body>    
   <?php 
    echo $this->layout()->content;
   ?>
</body>
</html>