    <tr>
        <th>Nom Prenom</th>
        <th>Login</th>
        <th>Commercial</th>
        <th>Acces externe</th>
        <th>Modifier</th>
    </tr>
<?php if (!$this->clients): ?>
    <tr><td colspan="5" align="center">Aucuns clients pour le moment</td></tr>
<?php else: ?>
    <?php foreach ($this->clients as $client): ?>
    <tr class="<?php echo ($client->getCliacces())? 'acces_enabled': 'acces_disabled'; ?>">
        <td><?php echo $client->getClirais();?> <?php echo $client->getClinom(); ?></td>
        <td><?php echo $client->getClilogin(); ?></td>
        <td><?php echo $this->utilisateurs[$client->getUtiid()]->getUtinom(); ?> <?php echo $this->utilisateurs[$client->getUtiid()]->getUtiprenom(); ?></td>
        <td><?php echo ($client->getCliacces())? 'Oui': 'Non'; ?></td>
        <td>
            <?php if ($client->getCliacces()): ?>
            <button type="button" id="<?php echo $client->getId(); ?>" class="disableAcces">
                <img alt="Autoriser l'acces distant" src="<?php echo $this->baseUrl('images/pictos/gris/hand_thumbsdown.png') ?>" width="32" height="32">
            </button>
            <?php else: ?>
            <button type="button" id="<?php echo $client->getId(); ?>" class="enableAcces">
                <img alt="Refuser l'acces distant" src="<?php echo $this->baseUrl('images/pictos/gris/hand_thumbsup.png') ?>" width="32" height="32">
            </button>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
<?php endif; ?>

<script type="text/javascript">
        
    var urlClientChangeAcces = "<?php echo $this->baseUrl('admin/clientchangeacces'); ?>";
    var urlClientList = "<?php echo $this->baseUrl('admin/clientlist'); ?>";
       
    $(document).ready(function(){
        $('.disableAcces').click(function(event) {
            var iD = $(this).attr('id');
            $.ajax({
                url:        urlClientChangeAcces,
                data: { modif: "disable", id: iD},
                type:       'POST',
                dataType:   'json',
                success: function(data) {
                    loadClient();
                },
                error : function(data){
//                    alert(data.responseText);
                }
            });
        }); 
        $('.enableAcces').click(function(event) {
            var iD = $(this).attr('id');
            $.ajax({
                url:        urlClientChangeAcces,
                data: { modif: "enable", id: iD},
                type:       'POST',
                dataType:   'json',
                success: function(data) {
                    loadClient();
                },
                error : function(data){
//                    alert(data.responseText);
                }
            });
        }); 
    });     
            
    
</script>
