<?php echo '<h1>' . $this->titre .'</h1>'; ?>
<div id="adminUser">
<p style="text-align: right; margin-right: 150px;">
    <a href="#" id="button_user_add" onclick="return false;">
        <img src="<?php echo $this->baseUrl("images/user_add.png"); ?>" style="width: 25px;" />
        Ajouter un nouvel utilisateur
    </a>
</p>
<br>
<table id="admin_user_table">

</table>
<div id="popup_user_add" style="display: none;">
    <table>
        <tr>
            <td colspan="2" id="user_add_error" style="display: none; color: red;">
                
            </td>
        </tr>
        <tr>
            <td colspan="2" id="user_add_success" style="display: none; color: green;">
                
            </td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td><input type="text" id="user_add_firstname"></td>
        </tr>
        <tr>
            <th>Nom</th>
            <td><input type="text" id="user_add_lastname"></td>
        </tr>
        <tr>
            <th>Login</th>
            <td><input type="text" id="user_add_login"></td>
        </tr>
        <tr>
            <th>Mot de passe</th>
            <td><input type="password" id="user_add_passwd1"></td>
        </tr>
        <tr>
            <th>Re-saisir mot de passe</th>
            <td><input type="password" id="user_add_passwd2"></td>
        </tr>
        <tr>
            <th>E-Mail</th>
            <td><input type="text" id="user_add_mail"></td>
        </tr>
        <tr>
            <th>Tel.</th>
            <td><input type="text" id="user_add_tel"></td>
        </tr>
    </table>
</div>
 <div id="popup_user_edit" style="display: none;">
     <input type="hidden" value="" id="user_edit_id">
     <table>
         <tr>
            <td colspan="2" id="user_edit_error" style="display: none; color: red;">
                
            </td>
        </tr>
        <tr>
            <td colspan="2" id="user_edit_success" style="display: none; color: green;">
                
            </td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td><input type="text" id="user_edit_firstname"></td>
        </tr>
        <tr>
            <th>Nom</th>
            <td><input type="text" id="user_edit_lastname"></td>
        </tr>
        <tr>
            <th>Login</th>
            <td><input type="text" id="user_edit_login"></td>
        </tr>
        <tr>
            <th>Mot de passe</th>
            <td><input type="password" id="user_edit_passwd1"></td>
        </tr>
        <tr>
            <th>Re-saisir mot de passe</th>
            <td><input type="password" id="user_edit_passwd2"></td>
        </tr>
        <tr>
            <th>E-Mail</th>
            <td><input type="text" id="user_edit_mail"></td>
        </tr>
        <tr>
            <th>Tel.</th>
            <td><input type="text" id="user_edit_tel"></td>
        </tr>
    </table>
</div>

<div id="popup_user_delete" style="display: none;">
    <p id="user_delete_error" style="display: none; color: red;"></p>
    <input type="hidden" value="" id="user_id">
    Voulez-vous vraiment supprimer l'utilisateur <b class="user_name"></b> ?
</div>
</div>
  
<style>
    label, input {
        display: inline;
        margin: 5px;
        
    }
    th {
        text-align: right;
    }
    td {
        text-align: left
    }
</style>

<script type="text/javascript">
    var urlUserChangeProfil = "<?php echo $this->baseUrl('admin/userchangeprofil'); ?>";
    var urlUserList = "<?php echo $this->baseUrl('admin/userlist'); ?>";
    var urlUserAdd = "<?php echo $this->baseUrl('admin/useradd'); ?>";
    var urlUserEdit = "<?php echo $this->baseUrl('admin/useredit'); ?>";
    var urlUserDelete = "<?php echo $this->baseUrl('admin/userdelete'); ?>";
       
    $(document).ready(function(){
        loadUser();
    });     
          
    $("#button_user_add").click(function() {
        $("#popup_user_add").dialog({
            modal : true,
            width : 500,
            buttons: {
                "Fermer" : function() {
                    $(this).dialog("close");
                },
                "Ajouter" : function() {
                    var error = '';
                    var success = '';
                    var firstname = $("#user_add_firstname").val();
                    var lastname = $("#user_add_lastname").val();
                    var login = $("#user_add_login").val();
                    var passwd1 = $("#user_add_passwd1").val();
                    var passwd2 = $("#user_add_passwd2").val();
                    var email = $("#user_add_mail").val();
                    var tel = $("#user_add_tel").val();
                    
                    $("#user_add_error").hide();
                    $("#user_add_success").hide();
                    if (login == '' || passwd1 == '') {
                        error = "Vous devez au moins saisir un login et un mot de passe";
                    } else if (passwd1 != passwd2) {
                        error = "Les deux mots de passe doivent etre identique";
                    }
                    if (error != '') {
                        $("#user_add_error").html(error).show();
                    } else {
                        $.ajax({
                            url:        urlUserAdd,
                            data:       { 
                                firstname: firstname,
                                lastname: lastname,
                                login: login,
                                passwd: passwd1,
                                email: email,
                                tel: tel
                            },
                            type:       'POST',
                            dataType:   'html',
                            success:    function(data) {
                                $("#user_add_error").hide();
                                $("#user_add_success").hide();
                                if (data == '') {
                                    $("#user_add_success").html("Utilisateur enregistre avec succes").show();
                                } else {
                                    $("#user_add_error").html(data).show();
                                }
                                $("#user_add_firstname").val('');
                                $("#user_add_lastname").val('');
                                $("#user_add_login").val('');
                                $("#user_add_passwd1").val('');
                                $("#user_add_passwd2").val('');
                                $("#user_add_mail").val('');
                                $("#user_add_tel").val('');
                            },
                            error :     function(data){
                                $("#user_add_success").hide();
                                $("#user_add_error").html(data).show();
                            }
                        });
                    }
                }
            },
            open: function(event, ui) {
                $("#user_add_firstname").val('');
                $("#user_add_lastname").val('');
                $("#user_add_login").val('');
                $("#user_add_passwd1").val('');
                $("#user_add_passwd2").val('');
                $("#user_add_mail").val('');
                $("#user_add_tel").val('');
                $("#user_add_success").hide();
                $("#user_add_error").hide();
            },
            close: function(event, ui) {
                loadUser();
            }
        });
    });
    
    
          
    function loadUser(){
        $.ajax({
            url:        urlUserList,
            type:       'POST',
            dataType:   'html',
            success: function(data) {
                $('#admin_user_table').html(data);
            },
            error : function(data){
//                alert(data.responseText);
            }
        });
    }
          
    
</script>
