<div id="home">
<?php
print_r($this->lol);
/*
 * Home
 */
echo '<h1>' . $this->titre .'</h1>';
?>
    <div id="homeSweetHome">
<p>
    Bonjour <b><?php $this->session->utinom ?></b>, bienvenue sur votre espace PlastProd.
</p>

<H2 style="margin-top:20px">PlastProd<H2>
<p style="margin-top:20px"><b>
    Notre entreprise est spécialisée dans la production d’éléments <br>en matières plastique à destination des constructeurs automobiles.
</b></p>
</div> 
</div>
