<?php
/*
 * Gestion des chaines
 */
echo '<h1>' . $this->titre . '</h1>';
?>
<div class="btnMat">
       <a href="#" onclick="createFormAddChain()">
          <img style="width:35px; height:35px;" src="<?php echo $this->baseUrl('images/ajouter.png'); ?>" alt="Ajouter une chaîne de production" title="Ajouter une chaîne de production" />
       </a> 
    </div>
<div id="listChain"> <!-- class="beautifulArray" -->

</div>

 <div style="display:none" id="detail">
</div>  
<script type="text/javascript">
   var urlModifChaines = "<?php echo $this->baseUrl('prod/disablechain'); ?>";
   var urlLoadChaines = "<?php echo $this->baseUrl('prod/chainprocesslist'); ?>";
       
    $(document).ready(function(){
        loadListChain();
    });     
            
    function loadListChain(){
        $.ajax({
            url:        urlLoadChaines,
            type:       'POST',
            dataType:   'html',
            success: function(data) {
                $('#listChain').html(data);
            },
            error : function(data){
                //alert(data.responseText);
            }
        });
    }        
          
    
</script>
